//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopXamarinTest.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevelopXamarinTest.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string AcceptBtn {
            get {
                return ResourceManager.GetString("AcceptBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorLbl {
            get {
                return ResourceManager.GetString("ErrorLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No internet connection.
        /// </summary>
        public static string NoInternetLbl {
            get {
                return ResourceManager.GetString("NoInternetLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pleace turn on your internet setting.
        /// </summary>
        public static string TurnOnInternetLbl {
            get {
                return ResourceManager.GetString("TurnOnInternetLbl", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Pleace turn on your internet setting.
        /// </summary>
        public static string ProductsLbl
        {
            get
            {
                return ResourceManager.GetString("ProductsLbl", resourceCulture);
            }
        }
        /// <summary>
        ///   Busca una cadena traducida similar a Pleace turn on your internet setting.
        /// </summary>
        public static string AddProductLbl
        {
            get
            {
                return ResourceManager.GetString("AddProductLbl", resourceCulture);
            }
        }
        /// <summary>
        ///   Busca una cadena traducida similar a Pleace turn on your internet setting.
        /// </summary>
        public static string DescriptionLbl
        {
            get
            {
                return ResourceManager.GetString("DescriptionLbl", resourceCulture);
            }
        }
        /// <summary>
        ///   Busca una cadena traducida similar a Pleace turn on your internet setting.
        /// </summary>
        public static string DescriptionPlaceholderTxt
        {
            get
            {
                return ResourceManager.GetString("DescriptionPlaceholderTxt", resourceCulture);
            }
        }
        /// <summary>
        ///   Busca una cadena traducida similar a Pleace turn on your internet setting.
        /// </summary>
        public static string PriceLbl
        {
            get
            {
                return ResourceManager.GetString("PriceLbl", resourceCulture);
            }
        }
        /// <summary>
        ///   Busca una cadena traducida similar a Pleace turn on your internet setting.
        /// </summary>
        public static string PricePlaceholderTxt
        {
            get
            {
                return ResourceManager.GetString("PricePlaceholderTxt", resourceCulture);
            }
        }
        /// <summary>
        ///   Busca una cadena traducida similar a Pleace turn on your internet setting.
        /// </summary>
        public static string RemarksLbl
        {
            get
            {
                return ResourceManager.GetString("RemarksLbl", resourceCulture);
            }
        }
        /// <summary>
        ///   Busca una cadena traducida similar a Pleace turn on your internet setting.
        /// </summary>
        public static string SaveBtn
        {
            get
            {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
    }
}
